version: '3'

services:
  app:
    build:
      context: .
    ports:
    - "8000:8000"
    volumes:
    - ./app:/app
    command: >
      sh -c "python python manage.py migrate &&s
                    python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=idresolutionGAIT
      - DB_USER=userGAIT
      - DB_PASSWORD=passwordGAIT
    depends_on:
      - db
  db:
    image: postgres:10-alpine
    environment:
      - POSTGRES_DB=idresolutionGAIT
      - POSTGRES_USER=userGAIT
      - POSTGRES_PASSWORD=passwordGAIT
