# Generated by Django 3.2.1 on 2021-05-04 16:38

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Xaxis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensordata', django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=5, max_digits=10), default=list, size=None)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=255)),
                ('xaxis', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.xaxis')),
            ],
        ),
    ]
