# Generated by Django 3.2.1 on 2021-05-04 16:41

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='xaxis',
        ),
        migrations.AddField(
            model_name='user',
            name='sensordata_x',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=5, max_digits=10), default=list, size=None),
        ),
        migrations.AddField(
            model_name='user',
            name='sensordata_y',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=5, max_digits=10), default=list, size=None),
        ),
        migrations.AddField(
            model_name='user',
            name='sensordata_z',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=5, max_digits=10), default=list, size=None),
        ),
        migrations.DeleteModel(
            name='Xaxis',
        ),
    ]
